diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=main
user.name=Jhonatan Mattana
user.email=jhonatan_mattana@outlook.com
gui.recentrepo=C:/Users/jhona/eclipse-workspace/power-motos
gui.recentrepo=C:/projetos/power-motos/java/eureka
gui.recentrepo=C:/projetos/power-motos/java/gateway
gui.recentrepo=C:/projetos/power-motos/java/menu
gui.recentrepo=C:/projetos/power-motos/java/power-motos-dto
gui.recentrepo=C:/projetos/power-motos/angular/powermotos-view-v15
gui.recentrepo=C:/projetos/power-motos/angular/powermotos-view-v13
gui.recentrepo=C:/Users/jhona/workspace-oficial/api-clinica
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.api-rest-spring-boot.url=https://github.com/JhonatanMattana/api-rest-spring-boot.git
remote.api-rest-spring-boot.fetch=+refs/heads/*:refs/remotes/api-rest-spring-boot/*
branch.main.remote=api-rest-spring-boot
branch.main.merge=refs/heads/main
gui.wmstate=normal
gui.geometry=893x435+104+104 175 196
